export const categories = [
    'Engineering',
    'Account Management',
    'Creative & Design',
    'Data Science',
    'Education',
    'Finance',
    'Healthcare',
    'Legal',
    'Operations',
    'Retail',
    'Social Media',
    'Business & Strategy',
    'Customer Service',
    'Editorial',
    'Fundraising & Development',
    'HR & Recruiting',
    'Marketing & PR',
    'Management',
    'Sales',
]